version: '3'
services: 
    # app: 
    #     container_name: 190715/node_aws_app
    #     restart: always
    #     build: .
    #     ports: 
    #         - '5050:5050'
    #     links: 
    #         - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - mongo-data:/data/db
    mongo-express:
        image: mongo-express
        ports:
            - 8084:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongo
    redis:
        image: redis
        # command: redis-server --requirepass sOmE_sEcUrE_pAsS
        ports: 
            - 6379:6379
        volumes:
            - redis_data:/data
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        
volumes:
    mongo-data:
        driver: local
    redis_data: